resources:
- manifests.yaml
- service.yaml
- deployment.yaml
- rbac.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: quay.io/sbahar/namespacelabel-webhook
  newTag: dev-42
